version: '3'
services:
  node:
    image: ${PROJECT_NAME}_node
    container_name: ${PROJECT_NAME}_node
    build:
      context: ./
      dockerfile: node.Dockerfile
    working_dir: /home/node/app
    env_file:
      - ".env"
    ports:
      - "${NODE_SSH}:22"
      - "${MAIN_FRONTEND}:8080"
      - "${MAIN_BACKEND}:8085"
    volumes:
      #NODE APPS:
      - ./node:/home/node/app
      #SHELL STUFF:
      - ./shell/bash_history/bash_history_node.sh:/root/.bash_history
      - ./shell/bash_profiles/general.sh:/root/.bash_profile
      - ./shell/.inputrc:/root/.inputrc
      - ./shell/.vimrc:/root/.vimrc
      - ./shell/terminal-coloring.sh:/root/terminal-coloring.sh
      - ./shell/darcula.vim:/root/.vim/colors/darcula.vim

  web:
    image: ${PROJECT_NAME}_nginx
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    container_name: ${PROJECT_NAME}_nginx
    working_dir: /var/www/html
    restart: always
    depends_on:
      - backend
    env_file:
      - ".env"
    ports:
      - "${NGINX_HTTP}:80"
      - "${NGINX_HTTPS}:443"
      - "${NGINX_SSH}:22"
    volumes:
      #CONFIG
      - ./nginx/config/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/global:/etc/nginx/global
      - ./nginx/config/snippets:/etc/nginx/snippets
      - ./nginx/config/ssl:/etc/nginx/ssl
      #logs
      - ./nginx/logs/:/var/log/nginx/
      #CONTENT
      - ./php/app:/var/www/html
      - ./node/public/main:/var/www/html/wp-content/themes/${PROJECT_NAME}/bundles/
      #SHELL STUFF:
      - ./shell/bash_history/bash_history_nginx.sh:/root/.bash_history
      - ./shell/bash_profiles/general.sh:/root/.bash_profile
      - ./shell/.inputrc:/root/.inputrc
      - ./shell/terminal-coloring.sh:/root/terminal-coloring.sh
      - ./shell/.vimrc:/root/.vimrc
      - ./shell/darcula.vim:/root/.vim/colors/darcula.vim


  backend:
    image: ${PROJECT_NAME}_php
    build:
      context: ./
      dockerfile: php.Dockerfile
    container_name: ${PROJECT_NAME}_php
    working_dir: /var/www/html
    restart: always
    depends_on:
      - db
    env_file:
      - ".env"
    ports:
      - "${PHP_SSH}:22"
    volumes:
      #CONTENT
      #uncomment after clean install
      - ./php/app:/var/www/html


      #run also rsync.sh to make these files available on host for git:
      #- ./node/public/main:/var/www/html/wp-content/themes/${PROJECT_NAME}/bundles/
      #- ./php/logs:/var/log

      #PHP CONFIG
      #- ./php/config/php-development.ini:/usr/local/etc/php/php.ini
      #outcomment if not needed, due to performance drop:
      #- ./php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/config/fpm-pool-setup.conf:/usr/local/etc/php-fpm.d/www.conf

      #SHELL STUFF:
      - ./shell/bash_history/bash_history_php.sh:/root/.bash_history
      - ./shell/bash_profiles/general.sh:/root/.bash_profile
      - ./shell/.inputrc:/root/.inputrc
      - ./shell/terminal-coloring.sh:/root/terminal-coloring.sh
      - ./shell/.vimrc:/root/.vimrc
      - ./shell/darcula.vim:/root/.vim/colors/darcula.vim

  db:
    cap_add:
      - SYS_NICE  # preventing mbind: operation not permitted error
    image: ${PROJECT_NAME}_mysql
    command: --default-authentication-plugin=mysql_native_password
    #Mac's with M1 chips:
    #platform: linux/amd64
    build:
      context: ./
      dockerfile: mysql.Dockerfile
    restart: always
    container_name: ${PROJECT_NAME}_mysql
    env_file:
      - ".env"
    ports:
      - "${MYSQL_SSH}:22"
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: ${PROJECT_NAME}
      MYSQL_PASSWORD: ${PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/custom.cnf:/etc/mysql/conf.d/custom.cnf
      #SHELL STUFF
      - ./shell/bash_history/bash_history_mysql.sh:/root/.bash_history
      - ./shell/bash_profiles/general.sh:/root/.bash_profile
      - ./shell/.inputrc:/root/.inputrc
      - ./shell/terminal-coloring.sh:/root/terminal-coloring.sh
      - ./shell/.vimrc:/root/.vimrc
      - ./shell/darcula.vim:/root/.vim/colors/darcula.vim